name: E2E Production

on:
  push:
    branches:
      - '*'
      # - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      uses: Quo0/puppeteer@7e61ac77d51a9eb21f1f9abbd16c8a0d14cedfc2
      with:
        args: npm ci
    - name: Run Puppeteer tests against jsnn.ru
      uses: Quo0/puppeteer@7e61ac77d51a9eb21f1f9abbd16c8a0d14cedfc2
      with:
        args: npm run e2e:ci
      env:
        TEST_PROD: true
